name: Build APT

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # We'll use a deploy token instead

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev devscripts

      - name: Run build script
        run: ./build.sh

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add dists pool
          git diff --quiet && echo "No changes to commit" && exit 0
          git commit -m "Update APT repo on build [skip ci]"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} main
